export const skills = [
  "TypeScript",
  "JavaScript",
  "React",
  "Next.js",
  "Node.js",
  "Express.js",
  "REST APIs",
  "MongoDB",
  "PostgreSQL",
  "Prisma",
  "NextAuth",
  "Zod",
  "TailwindCSS",
  "Docker",
  "CI/CD",
  "AWS",
  "Postman",
  "Git",
  "Data Structures",
  "C++",
];

export const projects = [
  {
    id: 1,
    title: "Text Behind Image",
    summary: [
      "Built an online editor for placing styled text behind uploaded images.",
      "Designed high-quality exports for social posts, banners, and creative visuals.",
      "Focused on simple controls, responsive UI, and fast browser-side interactions.",
    ],
    image: "/Textbehindimage.png",
    technologies: [
      "Next.js",
      "TailwindCSS",
      "Node.js",
      "Shadcn UI",
      "Convex DB",
    ],
    github: "https://github.com/YasirKhan231/",
    live: "https://www.textbehindimageonline.com/",
  },
  {
    id: 2,
    title: "PrepforLaw",
    summary: [
      "Created a Bar Exam preparation platform with subject-wise practice flows.",
      "Added AI-generated explanations, progress tracking, and law-focused analytics.",
      "Implemented authentication and structured learning modules for students.",
    ],
    image: "/barexam.png",
    technologies: [
      "TailwindCSS",
      "Node.js",
      "Next.js",
      "Firebase",
      "Shadcn UI",
      "NextAuth",
    ],
    github: "https://github.com/YasirKhan231/LSAT-training-",
    live: "https://lsat-training.vercel.app/",
  },
  {
    id: 3,
    title: "GitHub Profile README Generator",
    summary: [
      "Developed a generator for professional GitHub profile README files.",
      "Let developers add skills, social links, GitHub stats, and profile sections quickly.",
      "Used a polished UI to make README creation fast and beginner-friendly.",
    ],
    image: "/github-readme.png",
    technologies: [
      "Next.js",
      "TailwindCSS",
      "Framer Motion",
      "Shadcn UI",
      "TypeScript",
    ],
    github: "https://github.com/YasirKhan231/Github-profile-readme-generator",
    live: "https://github-profile-readme-generator-eight.vercel.app/",
  },
  {
    id: 4,
    title: "SmartExpense",
    summary: [
      "Built an expense tracker for daily spending, categories, and financial reporting.",
      "Added charts, insights, and report export features for quick decision-making.",
      "Connected database models with clean frontend flows for managing transactions.",
    ],
    image: "/expense.png",
    technologies: [
      "React.js",
      "TailwindCSS",
      "Next.js",
      "Prisma",
      "PostgreSQL",
      "Shadcn UI",
    ],
    github: "https://github.com/YasirKhan231/Expense-tracker",
    live: "https://expense-tracker-git-main-yasirkhan231s-projects.vercel.app/",
  },
  {
    id: 5,
    title: "CryptoPlace",
    summary: [
      "Created a cryptocurrency tracker with live market data for top coins.",
      "Displayed price charts and historical data using external API integrations.",
      "Built a responsive interface for scanning coin prices and market movement.",
    ],
    image: "/crypto.png",
    technologies: ["React.js", "TailwindCSS", "CoinGecko API", "Recharts"],
    github: "https://github.com/YasirKhan231/Crypto-tracker",
    live: "https://crypto-tracker-tau-eight.vercel.app/",
  },
  {
    id: 6,
    title: "ShinePro Windows - Landing Page",
    summary: [
      "Built a conversion-focused landing page for a window cleaning business.",
      "Added booking calls-to-action, pricing, testimonials, and service-area mapping.",
      "Structured the page for clear service discovery and lead generation.",
    ],
    image: "/window.png",
    technologies: ["Next.js", "TailwindCSS", "shadcn/ui", "Leaflet"],
    github: "https://github.com/YasirKhan231/window-clining-landing",
    live: "https://window-clining-landing.vercel.app/",
  },
  {
    id: 7,
    title: "Figma to Next.js - 45+ Pages",
    summary: [
      "Converted a large Figma design into a production-ready Next.js application.",
      "Created reusable components, typed routes, and responsive layouts.",
      "Delivered a pixel-focused AI reputation website across 45+ pages.",
    ],
    image: "/ai-reputation.png",
    technologies: ["Next.js", "TypeScript", "CSS"],
    github: "https://github.com/YasirKhan231",
    live: "https://ai-reputation-psi.vercel.app/",
  },
];

export const education = {
  college: "Arya College of Engineering and Technology",
  degree: "Computer Science and Engineering",
  duration: "2022 - 2026",
  points: [
    "Bachelor's degree focused on software development, algorithms, and system design.",
    "Built practical projects using full-stack web technologies and database systems.",
    "Strengthened fundamentals in programming, data structures, and application architecture.",
  ],
};

export const experiences = [
  {
    id: 1,
    company: "Filflo",
    role: "Software Developer",
    timeline: "Oct 2025 - Present",
    points: [
      "Developed end-to-end full-stack features, including scalable backend APIs, frontend interfaces, and system integrations.",
      "Built sales dashboards, analytics modules, and data visualizations to simplify business reporting and decision-making.",
      "Automated business workflows, including GRN processing and vendor portal integrations, reducing manual effort and improving efficiency.",
      "Collaborated with clients to gather requirements, deliver features on time, optimize performance, and resolve critical issues.",
    ],
  },
  {
    id: 2,
    company: "Startup Bricks",
    role: "Software Engineer Intern",
    timeline: "Jan 2025 - July 2025",
    points: [
      "Developed web applications using Next.js, React, Node.js, and REST APIs.",
      "Implemented frontend screens, backend routes, and reusable UI components.",
      "Worked with cross-functional teams to ship features and improve application quality.",
    ],
  },
  {
    id: 3,
    company: "Upwork & Fiverr",
    role: "Freelancer",
    timeline: "Mar 2025 - Oct 2025",
    points: [
      "Built MVPs, landing pages, dashboards, and consumer-facing websites for founders.",
      "Translated client requirements into clean user flows, components, and working products.",
      "Handled delivery, revisions, bug fixes, and deployment support across projects.",
    ],
  },
  {
    id: 4,
    company: "GirlScript Summer of Code",
    role: "Contributor",
    timeline: "Oct 2024 - Nov 2024",
    points: [
      "Contributed to open-source projects using JavaScript and TypeScript.",
      "Fixed bugs, improved components, and added small features through pull requests.",
      "Practiced collaborative development with maintainers and community contributors.",
    ],
  },
  {
    id: 5,
    company: "The Skill Guru Foundation",
    role: "Full Stack Developer",
    timeline: "Sep 2024 - Sep 2024",
    points: [
      "Developed web products for different foundation initiatives and business needs.",
      "Coordinated with the team to plan features, divide work, and complete software delivery.",
      "Worked across frontend, backend, and deployment tasks for full product execution.",
    ],
  },
];
